/*
 * File: board_config.h
 * 
 * This file contains macro defines to relating to the pin mappings of peripherals.
 * It is used to configure the board support package (BSP) for the mini flight computer.
 * 
 * Created: 2025
 */

 #ifndef BOARD_CONFIG_H
 #define BOARD_CONFIG_H

 //
// Board LED Definitions
//
#define LED_STATUS_GPIO_NUM GPIO_NUM_1
#define LED_STATUS_PIN LED_STATUS_GPIO_NUM
#define LED_STATUS_GPIO_MASK (1ULL << LED_STATUS_GPIO_NUM)

#define LED_CAN_TX_GPIO_NUM GPIO_NUM_2
#define LED_CAN_TX_PIN LED_CAN_TX_GPIO_NUM
#define LED_CAN_TX_GPIO_MASK (1ULL << LED_CAN_TX_GPIO_NUM)

#define LED_CAN_RX_GPIO_NUM GPIO_NUM_4
#define LED_CAN_RX_PIN LED_CAN_RX_GPIO_NUM
#define LED_CAN_RX_GPIO_MASK (1ULL << LED_CAN_RX_GPIO_NUM)

#define LED_SD_TX_GPIO_NUM GPIO_NUM_10
#define LED_SD_TX_PIN LED_SD_TX_GPIO_NUM
#define LED_SD_TX_GPIO_MASK (1ULL << LED_SD_TX_GPIO_NUM)

#define LED_SD_RX_GPIO_NUM GPIO_NUM_11
#define LED_SD_RX_PIN LED_SD_RX_GPIO_NUM
#define LED_SD_RX_GPIO_MASK (1ULL << LED_SD_RX_GPIO_NUM)


//
// PYRO Channel GPIO Definitions
//
#define PYRO_APO_1_GPIO_NUM GPIO_NUM_6
#define PYRO_APO_1_PIN PYRO_APO_1_GPIO_NUM
#define PYRO_APO_1_GPIO_MASK (1ULL << PYRO_APO_1_GPIO_NUM)

#define PYRO_APO_2_GPIO_NUM GPIO_NUM_7
#define PYRO_APO_2_PIN PYRO_APO_2_GPIO_NUM
#define PYRO_APO_2_GPIO_MASK (1ULL << PYRO_APO_2_GPIO_NUM)

#define PYRO_MAIN_1_GPIO_NUM GPIO_NUM_8
#define PYRO_MAIN_1_PIN PYRO_MAIN_1_GPIO_NUM
#define PYRO_MAIN_1_GPIO_MASK (1ULL << PYRO_MAIN_1_GPIO_NUM)

#define PYRO_MAIN_2_GPIO_NUM GPIO_NUM_9
#define PYRO_MAIN_2_PIN PYRO_MAIN_2_GPIO_NUM
#define PYRO_MAIN_2_GPIO_MASK (1ULL << PYRO_MAIN_2_GPIO_NUM)


//
// I2C Definitions
//
#define I2C_IMU_PORT I2C_NUM_0
#define I2C_IMU_SDA_GPIO_NUM GPIO_NUM_39
#define I2C_IMU_SDA_PIN I2C_IMU_SDA_GPIO_NUM
#define I2C_IMU_SCL_GPIO_NUM GPIO_NUM_40
#define I2C_IMU_SCL_PIN I2C_IMU_SCL_GPIO_NUM
#define I2C_IMU_INTERNAL_PULLUPS true
#define I2C_IMU_CLK_SPEED 100000 // 100 kHz

#define I2C_PRESS_PORT I2C_NUM_1
#define I2C_PRESS_SDA_GPIO_NUM GPIO_NUM_41
#define I2C_PRESS_SDA_PIN I2C_PRESS_SDA_GPIO_NUM
#define I2C_PRESS_SCL_GPIO_NUM GPIO_NUM_42
#define I2C_PRESS_SCL_PIN I2C_PRESS_SCL_GPIO_NUM
#define I2C_PRESS_INTERNAL_PULLUPS true
#define I2C_PRESS_CLK_SPEED 100000 // 100 kHz


//
// Sensor Definitions
//
#define SENSOR_IIS2MDC_I2C_ADDRESS (IIS2MDC_I2C_ADD >> 1) // 0x1E
#define SENSOR_IIS2MDC_CHIP_ID IIS2MDC_ID // 0x40U
#define SENSOR_IIS2MDC_I2C_PORT I2C_PRESS_PORT

#define SENSOR_LPS22DF_I2C_ADDRESS (LPS22DF_I2C_ADD_L >> 1) // 0x5C
#define SENSOR_LPS22DF_CHIP_ID LPS22DF_ID // 0xB4U
#define SENSOR_LPS22DF_I2C_PORT I2C_PRESS_PORT
#define SENSOR_LPS22DF_INT_GPIO_NUM GPIO_NUM_46
#define SENSOR_LPS22DF_INT_PIN SENSOR_LPS22DF_INT_GPIO_NUM

#define SENSOR_LSM6DSV80X_I2C_ADDRESS (LSM6DSV80X_I2C_ADD_L >> 1) // 0x6A
#define SENSOR_LSM6DSV80X_CHIP_ID LSM6DSV80X_ID // 0x73U
#define SENSOR_LSM6DSV80X_I2C_PORT I2C_IMU_PORT
#define SENSOR_LSM6DSV80X_INT1_GPIO_NUM GPIO_NUM_38
#define SENSOR_LSM6DSV80X_INT1_PIN SENSOR_LSM6DSV80X_INT1_GPIO_NUM


//
// CAN Definitions
//
#define CAN_RX_GPIO_NUM GPIO_NUM_36
#define CAN_RX_PIN CAN_RX_GPIO_NUM
#define CAN_RX_GPIO_MASK (1ULL << CAN_RX_GPIO_NUM)

#define CAN_TX_GPIO_NUM GPIO_NUM_37
#define CAN_TX_PIN CAN_TX_GPIO_NUM
#define CAN_TX_GPIO_MASK (1ULL << CAN_TX_GPIO_NUM)


//
// SD Card Definitions
//
#define SD_DATA0_GPIO_NUM GPIO_NUM_48
#define SD_DATA0_PIN SD_DATA0_GPIO_NUM
#define SD_DATA0_GPIO_MASK (1ULL << SD_DATA0_GPIO_NUM)

#define SD_DATA1_GPIO_NUM GPIO_NUM_35
#define SD_DATA1_PIN SD_DATA1_GPIO_NUM
#define SD_DATA1_GPIO_MASK (1ULL << SD_DATA1_GPIO_NUM)

#define SD_DATA2_GPIO_NUM GPIO_NUM_21
#define SD_DATA2_PIN SD_DATA2_GPIO_NUM
#define SD_DATA2_GPIO_MASK (1ULL << SD_DATA2_GPIO_NUM)

#define SD_DATA3_GPIO_NUM GPIO_NUM_26
#define SD_DATA3_PIN SD_DATA3_GPIO_NUM
#define SD_DATA3_GPIO_MASK (1ULL << SD_DATA3_GPIO_NUM)

#define SD_CLK_GPIO_NUM GPIO_NUM_34
#define SD_CLK_PIN SD_CLK_GPIO_NUM
#define SD_CLK_GPIO_MASK (1ULL << SD_CLK_GPIO_NUM)

#define SD_CMD_GPIO_NUM GPIO_NUM_47
#define SD_CMD_PIN SD_CMD_GPIO_NUM
#define SD_CMD_GPIO_MASK (1ULL << SD_CMD_GPIO_NUM)


 #endif // BOARD_CONFIG_H